//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Order_ID { get; set; }
        public Nullable<int> Asset_ID { get; set; }
        public Nullable<int> UserName_ID { get; set; }
        public Nullable<System.DateTime> ExpDeliveryDate_DT { get; set; }
        public Nullable<bool> OrderDone_BT { get; set; }
        public Nullable<System.DateTime> CreatedOn_DT { get; set; }
        public Nullable<System.DateTime> UpdatedOn_DT { get; set; }
        public Nullable<bool> IsActive_BT { get; set; }
        public Nullable<int> QtyOrdered_NB { get; set; }
    
        public virtual Asset_Details Asset_Details { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
